# Generated by Django 5.0.7 on 2025-11-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_unique_id', models.CharField(editable=False, help_text='System-generated unique org ID (ORG-XXXXXXXX)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Organization name', max_length=200)),
                ('legal_name', models.CharField(help_text='Legal/registered name', max_length=200)),
                ('email', models.EmailField(help_text='Organization contact email', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=20)),
                ('website', models.URLField(blank=True, help_text='Website URL')),
                ('address_line1', models.CharField(help_text='Address line 1', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='Address line 2', max_length=255)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State/Province', max_length=100)),
                ('postal_code', models.CharField(help_text='Postal/ZIP code', max_length=20)),
                ('country', models.CharField(default='United States', help_text='Country', max_length=100)),
                ('tax_id', models.CharField(help_text='Tax ID/EIN', max_length=50, unique=True)),
                ('registration_number', models.CharField(blank=True, help_text='Business registration number', max_length=50)),
                ('fiscal_year_start', models.DateField(help_text='Fiscal year start date')),
                ('currency', models.CharField(default='USD', help_text='Currency code (USD, EUR, INR, etc.)', max_length=3)),
                ('timezone', models.CharField(default='UTC', help_text='Timezone', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Is organization active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['org_unique_id'], name='organizatio_org_uni_2f7b2b_idx'), models.Index(fields=['is_active', 'created_at'], name='organizatio_is_acti_cad598_idx')],
            },
        ),
    ]
