# Generated by Django 5.0.7 on 2025-10-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_department_alter_document_options_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='logo_url',
        ),
        migrations.AlterField(
            model_name='organization',
            name='address_line1',
            field=models.CharField(help_text='Address line 1', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address_line2',
            field=models.CharField(blank=True, default='', help_text='Address line 2', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(help_text='City', max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.CharField(default='United States', help_text='Country', max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code (USD, EUR, INR, etc.)', max_length=3),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(help_text='Organization contact email', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='fiscal_year_start',
            field=models.DateField(help_text='Fiscal year start date'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is organization active'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='legal_name',
            field=models.CharField(help_text='Legal/registered name', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(help_text='Organization name', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Phone number', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(help_text='Postal/ZIP code', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='registration_number',
            field=models.CharField(blank=True, default='', help_text='Business registration number', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='state',
            field=models.CharField(help_text='State/Province', max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='tax_id',
            field=models.CharField(help_text='Tax ID/EIN', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Timezone', max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, default='', help_text='Website URL'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
