# Generated by Django 5.0.7 on 2025-11-10 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Role name', max_length=100)),
                ('level', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ORG_ADMIN', 'Organization Admin'), ('DEPT_ADMIN', 'Department Admin'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', help_text='Role hierarchy level', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Role description')),
                ('is_active', models.BooleanField(default=True, help_text='Is role active')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization (null for system-wide roles)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organizations.organization')),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_super_admin', models.BooleanField(default=False, help_text='System-wide superadmin (can manage all orgs)')),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=20)),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='avatars/')),
                ('is_2fa_enabled', models.BooleanField(default=False, help_text='Two-factor authentication enabled')),
                ('employee', models.OneToOneField(blank=True, help_text='Linked employee record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='employees.employee')),
                ('organization', models.ForeignKey(blank=True, help_text="User's organization", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='organizations.organization')),
                ('role', models.ForeignKey(blank=True, help_text="User's role", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='authentication.role')),
                ('user', models.OneToOneField(help_text='Django User', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
                'ordering': ['user__username'],
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['level', 'is_active'], name='roles_level_ed4165_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['organization', 'is_active'], name='roles_organiz_1c97c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'organization')},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['organization', 'role'], name='user_profil_organiz_659721_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_super_admin'], name='user_profil_is_supe_b42b47_idx'),
        ),
    ]
