# Generated by Django 5.0.7 on 2025-11-11 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='Django User', on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="Unique permission code (e.g., 'employee.create')", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable permission name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Permission description')),
                ('resource', models.CharField(help_text="Resource this permission applies to (e.g., 'employee', 'department')", max_length=100)),
                ('action', models.CharField(help_text="Action this permission allows (e.g., 'create', 'read', 'update', 'delete')", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['resource', 'action'],
                'indexes': [models.Index(fields=['resource', 'action'], name='permissions_resourc_2eec83_idx'), models.Index(fields=['code'], name='permissions_code_a0a529_idx')],
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions assigned to this role', related_name='roles', to='authentication.permission'),
        ),
    ]
