# Generated by Django 5.0.7 on 2025-11-10 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Department name', max_length=100)),
                ('code', models.CharField(help_text='Auto-generated unique department code (e.g., HR03, HR032)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Department description')),
                ('cost_center', models.CharField(blank=True, help_text='Cost center code for accounting', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Is department active')),
                ('organization', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('parent_department', models.ForeignKey(blank=True, help_text='Parent department (for hierarchy)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='employees.department')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(editable=False, help_text='Auto-generated unique employee identifier (EMP-XXXX-DEPT-123456)', max_length=50, unique=True)),
                ('first_name', models.CharField(help_text='First name', max_length=100)),
                ('middle_name', models.CharField(blank=True, help_text='Middle name', max_length=100)),
                ('last_name', models.CharField(help_text='Last name', max_length=100)),
                ('email', models.EmailField(help_text='Work email address', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('hire_date', models.DateField(help_text='Date of hire')),
                ('termination_date', models.DateField(blank=True, help_text='Date of termination (if applicable)', null=True)),
                ('job_title', models.CharField(help_text='Job title', max_length=200)),
                ('employment_type', models.CharField(default='FULL_TIME', help_text='Employment type (FULL_TIME, PART_TIME, CONTRACT)', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ON_LEAVE', 'On Leave'), ('TERMINATED', 'Terminated')], default='ACTIVE', help_text='Employment status', max_length=20)),
                ('address_line1', models.CharField(blank=True, help_text='Address line 1', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='Address line 2', max_length=255)),
                ('city', models.CharField(blank=True, help_text='City', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State/Province', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Postal code', max_length=20)),
                ('country', models.CharField(blank=True, help_text='Country', max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50)),
                ('department', models.ForeignKey(blank=True, help_text='Department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.department')),
                ('manager', models.ForeignKey(blank=True, help_text='Direct manager/supervisor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='employees.employee')),
                ('organization', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Document title', max_length=200)),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Employment Contract'), ('ID_PROOF', 'ID Proof'), ('EDUCATION', 'Educational Certificate'), ('EXPERIENCE', 'Experience Letter'), ('RESIGNATION', 'Resignation Letter'), ('PERFORMANCE_REVIEW', 'Performance Review'), ('OTHER', 'Other')], default='OTHER', help_text='Type of document', max_length=30)),
                ('file_key', models.CharField(help_text='Storage key/path for the file', max_length=500)),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(help_text='MIME type', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Document description')),
                ('version', models.IntegerField(default=1, help_text='Document version number')),
                ('is_archived', models.BooleanField(default=False, help_text='Is document archived')),
                ('organization', models.ForeignKey(help_text='Organization this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='organizations.organization')),
                ('replaces', models.ForeignKey(blank=True, help_text='Previous version of this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='employees.document')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Employee this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, help_text='Department head/manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to='employees.employee'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id'], name='employees_employe_0b5eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['organization', 'status'], name='employees_organiz_9abb4d_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'status'], name='employees_departm_9d2578_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['manager'], name='employees_manager_7cbad4_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['employee', 'document_type'], name='documents_employe_fcf392_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'is_archived'], name='documents_organiz_dd0bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_key'], name='documents_file_ke_3f01f9_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code'], name='departments_code_9f933a_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['organization', 'is_active'], name='departments_organiz_47d68a_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['parent_department'], name='departments_parent__cf33d4_idx'),
        ),
    ]
