# Generated by Django 5.0.7 on 2025-10-24 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organizations.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='document',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id'], name='employees_employe_0b5eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='employees_email_f66e96_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employment_status'], name='employees_employm_2e032a_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['organization', 'department'], name='employees_organiz_853c1f_idx'),
        ),
    ]
