# Generated by Django 5.0.7 on 2025-10-27 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_organiz_853c1f_idx',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_type',
        ),
        migrations.AddField(
            model_name='document',
            name='mime_type',
            field=models.CharField(default='application/octet-stream', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('RESUME', 'Resume'), ('CONTRACT', 'Contract'), ('ID_PROOF', 'ID Proof'), ('CERTIFICATE', 'Certificate'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_size',
            field=models.IntegerField(help_text='File size in bytes'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address_line1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address_line2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ON_LEAVE', 'On Leave'), ('TERMINATED', 'Terminated')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_email',
            field=models.EmailField(blank=True, default='', max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='preferred_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['organization', 'employment_status'], name='employees_organiz_4f239d_idx'),
        ),
    ]
